name: ci

on:
  pull_request:
  push:
    branches:
    - main
  workflow_call:

permissions:
  contents: read

defaults:
  run:
    shell: bash

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
        - windows-latest
        include:
        - docs: false
        - docs: true
          os: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up toolchain
      run: rustup show
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Test
      run: cargo test --all-features --workspace
    - name: Lint
      run: cargo clippy --all-features --all-targets --no-deps --workspace
    - name: Build documentation
      run: cargo doc --all-features --no-deps
    - name: Upload artifact
      if: ${{ matrix.docs }}
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc
